
export const PRODUCT_REQ = 'PRODUCT_REQ';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';


// Post 

export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';

// Patch 

export const PATCH_PRODUCT_SUCCESS = 'PATCH_PRODUCT_SUCCESS'
