
export const PRODUCTS_REQ = 'PRODUCTS_REQ';
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS';
export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE';


// POST 

export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';

// PATCH

export const PATCH_PRODUCT_SUCCESS = 'PATCH_PRODUCT_SUCCESS';