

export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';

export const TOGGLE_TODOS = 'TOGGLE_TODOS';