
export const TODO_REQUEST = 'TODO_REQUEST';
export const TODO_REQUEST_SUCCESS = 'TODO_REQUEST_SUCCESS';
export const TODO_REQUEST_FAILURE = 'TODO_REQUEST_FAILURE';

export const POST_TODO_REQUEST = 'POST_TODO_REQUEST';