
export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';


// Login

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
